version: '3'
services:
  app:
    build: .
    image: ssvirin/app
    container_name: ssvirin_app
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
    command: /avito
    depends_on:
      - db
      - cache

  db:
    image: postgres:16.2
    container_name: ssvirin_db
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  cache:
    image: redis:7.2.4
    container_name: ssvirin_cache
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
    command: redis-server

volumes:
  db:
  cache: